auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki/data
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2021-10-26  # Убедитесь, что эта дата актуальна
      store: tsdb         # Изменяем store на tsdb
      object_store: filesystem
      schema: v13        # Обновляем на v13
      index:
        prefix: index_
        period: 24h

limits_config:
  allow_structured_metadata: false  # Добавлено для устранения предупреждений

