server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: backend_file_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: backend
          __path__: /var/log/backend/app.log  # Путь к файлу внутри контейнера Promtail
    pipeline_stages:
      - json:  # Парсим JSON-логи
          expressions:
            level: levelname
            message: message
      - labels:
          level:  # Добавляем уровень лога как метку
